version: '3'

services:
    database:
        container_name: bitrix-database
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: sitemanager
            MYSQL_ROOT_PASSWORD: bitrix
            MYSQL_PASSWORD: bitrix
            MYSQL_USER: bitrix
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - bitrix
        ports:
            - 3306:3306
        volumes:
            - ./database/data:/var/lib/mysql
    nginx:
        image: ignashkins/bitrix-nginx
        privileged: true
        container_name: bitrix-nginx
        networks:
            - bitrix
        ports:
            - 80:80
            - 8895:8895
        volumes:
            - ./nginx/conf:/etc/nginx
            - ./www:/home/bitrix/www
            - ./bitrixenv_error:/var/www/bitrixenv_error
    apache:
        image: ignashkins/bitrix-apache
        privileged: true
        container_name: bitrix-apache
        networks:
            - bitrix
        volumes:
            - ./www:/home/bitrix/www
            - ./apache/conf:/etc/httpd
            - ./apache/php.d:/etc/php.d
        ports:
            - 8888:8888
            - 8887:8887
            - 9887:9887
    push-server:
        image: ignashkins/bitrix-push-server
        container_name: bitrix-node
        networks:
            - bitrix
        ports:
            - 8010:8010
            - 8011:8011
            - 8012:8012
            - 8013:8013
            - 8014:8014
            - 8015:8015
            - 9010:9010
            - 9011:9011
networks:
    bitrix:
        driver: bridge